# For NodeJS Environment
name: CICD - NodeJS
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    # name: Build & Test on Node.js ${{ matrix.node_version }} and ${{ matrix.os }}
    # runs-on: ${{ matrix.os }}
    # strategy:
    #   matrix:
    #     node_version: ['lts/*']
    #     os: ['ubuntu-latest']

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node_version: 'lts/*'
          # node_version: ${{ matrix.node_version }}
      
      - name: yarn install, build and test
        run: |
          yarn --frozen-lockfile
          yarn build

      - name: Zip artifact for deployment
        run: zip helloworld.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: helloworld.zip

      # # Runs a single command using the runners shell
      # - name: Run a one-line script
      #   run: echo Hello, world!

      # # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Set current date
        run: echo "CURRENT_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Deploy to VM instance
        env:
          PEM_KEY: ${{ secrets.AZURE_VM_PEM }}
          PEM_KEY_FILE: 3rd-prj-team3-eastus2-vm.pem
        run: |
          echo "$PEM_KEY" >> $HOME/$PEM_KEY_FILE
          chmod 400 $HOME/$PEM_KEY_FILE
          
          scp -i $HOME/$PEM_KEY_FILE -o StrictHostKeyChecking=no -r ./* azureuser@20.55.199.98:/home/azureuser/GithubActions/
          
          
